######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 1 23:25:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

CORE_DIR = ../core

INCLUDEPATH += include /usr/local/include /usr/include $$CORE_DIR/include

LIBS += -lGL -lglut -lopencv_core -L$$CORE_DIR -lneurogoats -lOpenCL

QT += opengl

# Input
SOURCES += StreamScreen.cpp main.cpp
